name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.5, 3.6]
        pattern: [stable]  # see test-unstabl-workarounde.yml
        # pattern: [stable, unstable]
        exclude:
        - os: windows-latest
          python-version: 3.6
        - os: macos-latest
          python-version: 3.6



    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get pip cache
      id: pip-cache
      run: |
        python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}-${{ hashFiles('setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip3 install --upgrade setuptools
        pip3 install .[dev]

    - name: Load balancing
      id: load-balancing
      run: |
          python -m tests.load_balancer ${{ matrix.pattern }}

    - name: Run tests
      run: |
        oj-api -h
        pytest -v ${{ steps.load-balancing.outputs.files }}
